Repository hjaremko/asciinem, pull requests merged in 2020-12, with the labels that each got.

#1 Setup GitHub actions
  .github/workflows/build.yml
  cmake/conan.cmake
  cmake/static_analyzers.cmake
  src/client/main.cpp
  test/CMakeLists.txt
  test/constexpr_tests.cpp
  test/tests.cpp
Labels: enhancement

#3 Merge sanitizer workflows
  .github/workflows/asan.yml
  .github/workflows/build.yml
  .github/workflows/lsan.yml
  .github/workflows/sanitizers.yml
  .github/workflows/tidy.yml
  .github/workflows/tsan.yml
  .github/workflows/ubsan.yml
  .github/workflows/verify.yml
Labels: enhancement

#5 Include some CMake options in README
  README.md
Labels: documentation

#14 Implement server clock
  CMakeLists.txt
  cmake/conan.cmake
  include/server/network/clock.hpp
  include/server/network/interfaces/observer.hpp
  include/server/network/interfaces/subject.hpp
  src/server/CMakeLists.txt
  test/CMakeLists.txt
  test/client/tests.cpp
  test/server/clock_tests.cpp
  test/server/tests.cpp
Labels: enhancement, wp

#4 Partially implement network listener
  include/server/network/asio_connection.hpp
  include/server/network/asio_listener.hpp
  include/server/network/asio_tcp_server.hpp
  include/server/network/interfaces/client_connection.hpp
  include/server/network/interfaces/connection_manager.hpp
  include/server/network/interfaces/listener.hpp
  include/server/network/interfaces/network_manager.hpp
  include/server/network/types.hpp
  src/server/CMakeLists.txt
  src/server/main.cpp
  src/server/network/asio_connection.cpp
  src/server/network/asio_listener.cpp
  src/server/network/asio_tcp_server.cpp
  test/CMakeLists.txt
  test/server/network/clock_tests.cpp
  test/server/network/listener_tests.cpp
  test/server/network/mocks/connection_manager_mock.hpp
  test/server/tests.cpp
Labels: enhancement, wp

#17 Treat warnings as errors, fix clang-tidy warnings
  .clang-tidy
  cmake/compiler_warnings.cmake
  include/server/network/asio_listener.hpp
  include/server/network/asio_tcp_server.hpp
  src/server/network/asio_connection.cpp
  src/server/network/asio_tcp_server.cpp
  test/server/network/clock_tests.cpp
  test/server/network/listener_tests.cpp
Labels: improvement

#18 Implement data receiving
  include/server/network/asio_connection.hpp
  include/server/network/asio_listener.hpp
  include/server/network/asio_server.hpp
  src/server/CMakeLists.txt
  src/server/network/asio_connection.cpp
  src/server/network/asio_server.cpp
  test/CMakeLists.txt
  test/server/network/listener_tests.cpp
Labels: enhancement

#19 Implement message queue
  .github/workflows/build.yml
  .github/workflows/sanitizers.yml
  .github/workflows/verify.yml
  include/server/network/interfaces/queue.hpp
  include/server/network/message_queue.hpp
  src/server/CMakeLists.txt
  src/server/network/message_queue.cpp
  test/CMakeLists.txt
  test/server/network/queue_tests.cpp
Labels: enhancement

#16 Implement database connection
  cmake/conan.cmake
  include/server/db/database.hpp
  include/server/db/query_result_type.hpp
  include/server/db/sqlite_connection.hpp
  include/server/db/types.hpp
  src/server/CMakeLists.txt
  src/server/db/sqlite_connection.cpp
  test/CMakeLists.txt
  test/server/db/sqlite_tests.cpp
Labels: enhancement, wp

#20 Implement connection manager with receiving capability
  include/server/network/asio_connection.hpp
  include/server/network/asio_manager.hpp
  include/server/network/asio_server.hpp
  include/server/network/id_pool.hpp
  include/server/network/interfaces/client_connection.hpp
  include/server/network/interfaces/connection_manager.hpp
  include/server/network/interfaces/queue.hpp
  src/server/CMakeLists.txt
  src/server/main.cpp
  src/server/network/asio_connection.cpp
  src/server/network/asio_manager.cpp
  src/server/network/asio_server.cpp
  test/CMakeLists.txt
  test/server/network/connection_manager_tests.cpp
  test/server/network/listener_tests.cpp
  test/server/network/mocks/client_connection_mock.hpp
  test/server/network/mocks/connection_manager_mock.hpp
  test/server/network/mocks/queue_mock.hpp
Labels: enhancement

#21 Add broadcasting capability to the connection manager
  include/server/network/asio_manager.hpp
  include/server/network/clock_observer.hpp
  include/server/network/interfaces/connection_manager.hpp
  src/server/main.cpp
  src/server/network/asio_manager.cpp
  test/server/network/connection_manager_tests.cpp
  test/server/network/mocks/clock_mock.hpp
  test/server/network/mocks/connection_manager_mock.hpp
  test/server/network/mocks/queue_mock.hpp
Labels: enhancement

#23 Implement Network module facade and its factory
  .github/workflows/verify.yml
  include/server/network/asio_factory.hpp
  include/server/network/asio_listener.hpp
  include/server/network/asio_manager.hpp
  include/server/network/asio_network.hpp
  include/server/network/asio_server.hpp
  include/server/network/clock.hpp
  include/server/network/interfaces/connection_manager.hpp
  include/server/network/interfaces/listener.hpp
  include/server/network/interfaces/network_factory.hpp
  include/server/network/interfaces/network_module.hpp
  include/server/network/server_config.hpp
  src/server/main.cpp
  src/server/network/asio_connection.cpp
  src/server/network/asio_listener.cpp
  src/server/network/asio_manager.cpp
  src/server/network/asio_server.cpp
  test/server/network/connection_manager_tests.cpp
  test/server/network/listener_tests.cpp
Labels: server, wp

#25 Add command line options that set port and logging level
  cmake/conan.cmake
  include/server/network/asio_network.hpp
  include/server/network/interfaces/network_factory.hpp
  include/server/network/server_config.hpp
  include/server/util.hpp
  src/server/CMakeLists.txt
  src/server/main.cpp
  src/server/util.cpp
Labels: improvement, server

#28 Improve macOS compatibility
  cmake/compiler_warnings.cmake
  include/client/network/asio_network_module.hpp
  include/server/network/asio_connection.hpp
  include/server/network/interfaces/subject.hpp
Labels: improvement
